### ISSUE TITLE
Interaction forces 

### ISSUE THREAD

**Issue by elisaiovene** [WPI-AIM/ambf#116]
Hello Adnan, 

I'm teleoperating the Kuka robot in simulation with the Omni Phantom. The Omni is not defined in the input_devices.yaml but is ran as an independent node. 
I would like to implement the haptic feedback such that I can sense the forces that occurs on the Kuka tip or on the link7.
To get information about the interaction forces between rigid bodies in the environment I just enable the feedback of the last joint in the ADF. Should I do something else?
Now, if I subscribe to the /State topic I can read the values, however if I print for example the z-axis force when 2 object collide, I get values of about -40/-50. Is this normal? Because I feel is too big for sending it directly to the Omni. 
Moreover, if the tip and another object collide, the kuka sometimes disappears. 

Finally, is there a way to display the force? 

I'm sorry this is more a question than an issue, but I hope you can help me!
Thanks!

**Comment by adnanmunawar** [comment]
Hi Elisa,
I'd be happy to help. Yes, you may point a fixed joint in between and enable force feedback on it. A couple of things to be aware of though:
1. Is your last joint a fixed one or a revolute one? Probably better to have a fixed joint for sensing force feedback
2. The forces are sent out resolved in the body frame, not in the World frame, so make sure to use the body's rotation matrix to reorient the force back to the world coordinates. 
3. The forces should never be directly applied to the device. There should be a safety logic that never lets the force exceed the max allowed force on the device. You can find that out by either using the device specifications or manually ramping the forces. Also, you should be using a scale factor to scale down the forces, which depends upon your implementation.
4. What do your collisions look like? Are you using primitives? If not, is the environment mesh too high resolution? Please share your model here so we can take a look at it.

**Comment by elisaiovene** [comment]
Hello Adnan, 
Thanks for your reply! 
1. My last joint (link7-kuka_tip) is a revolute one. Should I add a fixed joint and use that as reference? 
2. So the force/torque I receive from the /State topic of link7 should be multiplied by the rotation matrix, am I right? Also, can I ask why I need them wrt the world's reference system? 
4. Yes, I'm using primitives for both kuka and the cylinders it collides with. Anyway I've shared the model.
Thanks!  

[models.zip](https://github.com/WPI-AIM/ambf/files/6039159/models.zip)

**Comment by adnanmunawar** [comment]
1. I see in the blender-kuka-tip ADF that the joint between the link7-tip is a fixed joint. That is good, so no need to change anything there.
2. The reason being that for most haptic devices, (geomagic for sure), you supply the feedback force in a fixed reference frame that is the device's base frame. If you imagine the force from the simulation to always be in the body frame (as it currently is), image trying to touch a cube with the kuka_tip with the condition that the kuka_tip always points normal to the cube's face that you want to touch. Let's also assume that the kuka_tip has +ve Z along the tip. Now if you touch the front face, right face or left face of the cube, the body force is always going to be along the -ve Z direction (or +ve Z direction depending upon how the force sensor is set up) of the kuka_tip. However, your haptic feedback force should be backwards (for front face), towards left (for the right face) and towards right (for the left face). Thus you cannot directly use the body force. Now that being said, after you convert the body force to the world frame, you still need to make sure that the simulation world frame is aligned with the device's base frame as otherwise the haptic response would not make sense. In summary you first need to multiply the force with the body rotation matrix in the simulation world frame and then the rotation of the simulation world frame in device's base frame. 
```f_d = R_w^d * R_b^w * f_b```
There are many ways on how you can figure out what R_w^d (the orientation of simulation world in device's base frame) is.
3. I was not able to load the task.yaml ADF. Perhaps the meshes are not correct.

**Comment by elisaiovene** [comment]
Ok, so first I align the reference frame of the last joint with the word reference frame (R_b^w) in simulation, then I align the reference frame of the word with the one of the base of the Omni (R_w^d). Doing so I get F_d. 
After that, this force should be scaled and sent to the Omni.  

Yes, sorry I attached the wrong meshes. Here is the right one
[models.zip](https://github.com/WPI-AIM/ambf/files/6042658/models.zip)

**Comment by adnanmunawar** [comment]
The models still seem to have incorrect paths, anyway, I fixed them. 
I noticed a few issues with the individual ADFs.
1. In task.yaml, the collisions for the number shapes were set to primitive with zero x,y,z dimensions. Not sure what you had in mind but that would cause the inertia estimation of that body to come up with (0, 0, 0) which is invalid and thus any collision with that body will cause the non-static bodies (kuka in this case) to dissapear.
2. In blender-kuka-tip-sphere.yaml, the collision offset of the tip_ball and kuka_tip were off, I fixed them. Also, the mass of the tip_ball was set to 0.001 and this resulted in a (0, 0, 0) inertia estimation, which is also invalid. The reason your model did not always disappear is because the collision shape of your kuka_tip overlapped the tip_ball's collision shape which prevented the tip_ball to collide at certain configurations. Anyway, I fixed those offsets.
3. In blender-kuka-tip-sphere.yaml, your joint limits for Joint link7-kuka_tip were incorrect, as the limits are taken from the current configuration, thus -118 to 118 from the already rotated link 7 were not feasible. 

Here is an updated zipped file with the newer models. I also added a stand alone launch and world file with 0 gravity for easier testing.

You can run it as 

```bash
./ambf_simulator --launch_file <path_to_folder>/launch_file.yaml -l 0,1 -n0 -p60 -t1
```

**Comment by elisaiovene** [comment]
Hello Adnan,
thanks for fixing the models. Anyway I can't see the zip file, can you share it again please? 
thanks

**Comment by adnanmunawar** [comment]
Sorry about that, I just edited the comment with the files attached.

**Comment by Zimmo95** [comment]
Hi Adnan, 
I followed the istructions of "interaction force" issue.
I enabled the force feedback on the tip and created a collision shape

Enrico

![Screenshot from 2021-04-09 12-24-21](https://user-images.githubusercontent.com/74068406/114167331-1a60db80-992f-11eb-9f97-214e986d163a.png)
![Screenshot from 2021-04-09 12-23-43](https://user-images.githubusercontent.com/74068406/114167344-1c2a9f00-992f-11eb-8c7b-b94b1ba9193f.png)

 (singular shape-sphere) and created a fixed joint but I don't have the feedback and the force values of the tip are very strange.
