### ISSUE TITLE
Fix CMake out-of-source build

### ISSUE THREAD

**Issue by pkazanzides** [WPI-AIM/ambf#201]
The AMBF instructions suggest building in a subfolder of the source tree, but the more conventional CMake approach is to have the build tree separate from the source tree.  However, choosing a separate build tree does not produce the expected result, since some of the build files are placed in the source tree.  Specifically, the `bin` folder appears in the source tree.

**Comment by kschwan** [comment]
Hi,
I think the changes in 189cb5ec8b7ae03b12c0e215d5f67c26c31f6ffe are bad because you are now putting binaries outside both the build folder _and_ the source folder :)

You can try:
```
mkdir -p ~/tmp/ambf-build
cd ~/tmp/ambf-build
cmake ~/path-to-ambf-source
make
```
You now have binaries in `~/tmp/bin`.

I believe 189cb5ec8b7ae03b12c0e215d5f67c26c31f6ffe should be reverted while 40b3efaac4f904767afd081fa0730ae39b88cfad should stay.

**Comment by kschwan** [comment]
@adnanmunawar not sure if you're notified on a closed issue, so just to be sure...

**Comment by adnanmunawar** [comment]
Hi Kim, thanks for your comment. I agree with you, the reason for the second commit, i.e. creating a `bin` just outside the `build` folder, was to keep all the launch instructions in READMEs on our multiple repositories valid. As you noted, the correct way is to keep the previous commit, but updating the READMEs will need to be done simultaneously. :)
