### ISSUE TITLE
ArmParallel - BottomArm joint missing in AMBF for the MTM though defined in the YAML

### ISSUE THREAD

**Issue by sapan-ostic** [WPI-AIM/ambf#38]
The YAML file for the MTM has the description for the joint Arm Parallel - Bottom Arm. However, the joint does not appear in the state object i.e. the joint doesn't appear in get_joint_names(). 
Thus, neither the joint can be commanded nor any feedback can be obtained.

**Comment by adnanmunawar** [comment]
As we discussed separately, at the moment, the internal implementation only considers one child-joint pair. If a child has been already added to a parent body's map, and another joint with the same child is being added, we will skip adding that joint for reporting or control purposes. The thought process behind this was that since this shall result in a closed loop mechanism any-way, we can control the mechanism using the joints already appended to the parent body. In the future, however, we can change this to allow the addition of extra joints between the same parent and child.

To solve your specific problem, you can change the order of joints in the description file of your robot. So the joint that you're interested in controlling occurs prior to other joints forming the closed loop mechanism. You don't have to move the actual definition of the joint, only the joint's name in the header list in the beginning of the file.
